# Generated by Django 4.0.4 on 2022-10-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URl')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'World women categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URl')),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='time update')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Popular Women',
                'verbose_name_plural': 'Popular Women',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
