# Generated by Django 4.0.4 on 2022-12-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_contactadmin_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='PostModel',
        ),
    ]
